name: Test tags
on:
  push:
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.sha }}
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.ref_name }}
      - run: echo ${{ github.ref_type }}
      - run: echo ${{ github.repository }}
      - run: echo ${{ github.repository_owner }}
      - run: echo ${{ github.run_id }}
      - run: echo ${{ github.run_number }}
