name: Test working directory
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test-path
    steps:
      - name: test
        working-directory: ""
        run: echo "hi"
